### ISSUE TITLE
Difference between pages and components

### ISSUE THREAD

**Issue by pierreguerin0341** [flatlogic/sing-app-vue-dashboard#1]
Hi!

Currently using this template for my own project (Got you in the credits buddy :D)
Anyway, I am trying to do a Axios call from the Dashboard but somehow it's not executing(API not showing anything inside the log)
However, when I execute this method inside the Layout.vue inside the component folders it does actually consume the API.

I would like to know how I can consume the API through the Dashboard page/component.
Which brings me to the next question.. ;) 
Can you tell me the difference between the pages and the components? It's literally the same code right? 

Thanks in advance!

**Comment by keksonov** [comment]
Hi,

Component it's a reusable component. It means you can import component in any place of your app and it will work as expected. Page is literally page of your dashboard (eg charts or inbox).
