### ISSUE TITLE
Theme.scss

### ISSUE THREAD

**Issue by mohamedeways** [flatlogic/sing-app-vue-dashboard#11]
Error: File "/node_modules/bootstrap/scss/bootstrap" not found
        on line 6 of sass

**Comment by tigerblue77** [comment]
I've got more or less the same problem, posted it [here](https://www.reddit.com/r/bootstrap/comments/inne3u/error_eisdir_file_is_a_directory_node/) and [here](https://stackoverflow.com/questions/63765311/error-eisdir-file-is-a-directory-node-modules-bootstrap-scss-mixins-code)

**Comment by Blari** [comment]
Fixed
