### ISSUE TITLE
Question: what does "backend support" mean? Where can i find docs?

### ISSUE THREAD

**Issue by micksp** [flatlogic/sing-app-vue-dashboard#12]
From the readme: 

> If you use app with backend support, please use
> yarn run serve:backend

I can't find this script entry and I do not know what is meant by "backend support" Perhaps a nuxt version somewhere? 
Is there any documentation for this framework, apart from the pointers on the pages in the source code?

**Comment by Blari** [comment]
We apologize. It was an error.
Backend support is available in [full version](https://flatlogic.com/templates/sing-app-vue/demo) only.
