### ISSUE TITLE
asset size exceed the recommended size when i run build

### ISSUE THREAD

**Issue by robertobirijnr** [flatlogic/sing-app-vue-dashboard#18]
asset size limit: The following asset(s) exceed the recommended size limit (391 KiB).
This can impact web performance.
Assets:
  img/Flaticon.686496bc.svg (1.08 MiB)
  img/fontawesome-webfont.912ec66d.svg (434 KiB)
  img/la-brands-400.9769d0a6.svg (906 KiB)
  img/la-solid-900.79be4e9f.svg (902 KiB)
  js/chunk-vendors.80c9d337.js (1.22 MiB)

 warning

entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (391 KiB). This can impact web performance.
Entrypoints:
  app (1.77 MiB)
      css/chunk-vendors.1119994d.css
      js/chunk-vendors.80c9d337.js
      css/app.07f0ee8b.css
      js/app.d43bd9e5.js

**Comment by Blari** [comment]
Fixed. Thanks! )
