### ISSUE TITLE
Error: EISDIR: File is a directory., '/node_modules/bootstrap/scss/mixins' (CodeSandbox / Bootstrap / VueJS)

### ISSUE THREAD

**Issue by tigerblue77** [flatlogic/sing-app-vue-dashboard#19]
Hi everyone,

I'm a bit new to all of those web techs (CodeSandbox, Bootstrap and VueJS) but I learn fast. After doing a lot of research, I wanted to start my web platform project with [this project template](https://flatlogic.com/templates/sing-app-vue-dashboard) to have a good base and a good structure but I'm stuck with this error :

> Cannot find module 'bootstrap/scss/mixins' from '/src/styles'

And when I look in the file containing the "import" directive :

> Error: Error: EISDIR: File is a directory., '/node_modules/bootstrap/scss/mixins'
on line 10:9 of node_modules/bootstrap/scss/bootstrap.scss
from line 10:2 of /stdin
\>> u/import "mixins";

I understand that "mixins" is a directory, okay, but it's the bootstrap code man... I cannot change it on codesandbox and after checking on [bootstrap github's repository](https://github.com/twbs/bootstrap), it seems normal that "mixins" is a directory.

You can check the code sandbox [here](https://codesandbox.io/s/funny-bohr-jp804) (no changes made, project just imported, modules not updated, I tried but it changed nothing). The file containing all import directives is src/styles/themes.scss [direct link](https://codesandbox.io/s/funny-bohr-jp804?file=/src/styles/theme.scss).

Thanks by advance for your help ! :)

**Comment by tigerblue77** [comment]
Hello @Blari ,

I saw you fixed many issues on this today so I've updated my sandbox (still accessible following the link in my issue description)
But I still have the problem :

> Cannot find module 'bootstrap/scss/mixins' from '/src/styles'

**Comment by Blari** [comment]
You can write to me in telegram? @blari ?)

**Comment by tigerblue77** [comment]
Sorry I don't use this application, do you have something else ?
If not, I'll create an account

**Comment by Blari** [comment]
mb Facebook? )
https://www.facebook.com/blarior

**Comment by tigerblue77** [comment]
Hello,
Thanks @Blari for your help, as we don't know why the code sandbox won't work with this template I'll close my issue and post the script I used to mount/prepare my Debian VM to code :

`# NodeJS installation
# https://github.com/nodejs/help/wiki/Installation
VERSION=v14.15.0
DISTRO=linux-x64
wget https://nodejs.org/dist/$VERSION/node-$VERSION-$DISTRO.tar.xz
mkdir -p /usr/local/lib/nodejs
tar -xJvf node-$VERSION-$DISTRO.tar.xz -C /usr/local/lib/nodejs

nano ~/.profile

# Add to the end of file :

# Nodejs
VERSION=v14.15.0
DISTRO=linux-x64
export PATH=/usr/local/lib/nodejs/node-$VERSION-$DISTRO/bin:$PATH

. ~/.profile

# Test :

node -v
npm version
npx -v

# Install GIT
apt install git -y

# Clone the project
git clone https://github.com/flatlogic/sing-app-vue-dashboard.git

cd sing-app-vue-dashboard/
npm i

# Launch the devloppment server
npm run serve

# Install VScode :
wget https://update.code.visualstudio.com/1.50.1/linux-deb-x64/stable
dpkg -i code_1.50.1-1602600906_amd64.deb`

**Comment by tigerblue77** [comment]
Hello,
Thanks @Blari for your help, as we don't know why the code sandbox won't work with this template I'll close my issue and post the script I used to mount/prepare my Debian VM to code :

```bash
# NodeJS installation
# https://github.com/nodejs/help/wiki/Installation
VERSION=v14.15.0
DISTRO=linux-x64
wget https://nodejs.org/dist/$VERSION/node-$VERSION-$DISTRO.tar.xz
mkdir -p /usr/local/lib/nodejs
tar -xJvf node-$VERSION-$DISTRO.tar.xz -C /usr/local/lib/nodejs

nano ~/.profile

# Add to the end of file :

# Nodejs
VERSION=v14.15.0
DISTRO=linux-x64
export PATH=/usr/local/lib/nodejs/node-$VERSION-$DISTRO/bin:$PATH

. ~/.profile

# Test :

node -v
npm version
npx -v

# Install GIT
apt install git -y

# Clone the project
git clone https://github.com/flatlogic/sing-app-vue-dashboard.git

cd sing-app-vue-dashboard/
npm i

# Launch the devloppment server
npm run serve

# Install VScode :
wget https://update.code.visualstudio.com/1.50.1/linux-deb-x64/stable
dpkg -i code_1.50.1-1602600906_amd64.deb
```

Thanks again
