### ISSUE TITLE
Error when running npm run serve

### ISSUE THREAD

**Issue by andriasmelianus** [flatlogic/sing-app-vue-dashboard#2]
Hi..
I found this error when I try to run `npm run serve` or `yarn run serve.`
```
 ERROR  Failed to compile with 2 errors                                                  8:02:39 PM

These dependencies were not found:

* imports-loader?jQuery=jquery,this=>window!jquery.flot-orderBars/js/jquery.flot.orderBars in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/Charts/Charts.vue?vue&type=script&lang=js&
* imports-loader?jQuery=jquery,this=>window!jquery.flot.animator/jquery.flot.animator in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/Charts/Charts.vue?vue&type=script&lang=js&

To install them, you can run: npm install --save imports-loader?jQuery=jquery,this=>window!jquery.flot-orderBars/js/jquery.flot.orderBars imports-loader?jQuery=jquery,this=>window!jquery.flot.animator/jquery.flot.animator

```
What can I do to fix this?
Thanks

**Comment by mansouryaacoubi** [comment]
![image](https://user-images.githubusercontent.com/6348858/53011371-80810080-3440-11e9-9df8-3494e9e2072b.png)

And I got this error running `npm run serve` or `npm run build`.

**Comment by elioclimaco** [comment]
Yes, same error, please fix them, I like the Dashboard, even mi boss it's agree with the implementation, but, don't run.

These dependencies were not found:

* core-js/modules/es6.regexp.to-string in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/Charts/Charts.vue?vue&type=script&lang=js&
* core-js/modules/es7.promise.finally in ./src/main.js
* imports-loader?jQuery=jquery,this=>window!jquery.flot-orderBars/js/jquery.flot.orderBars in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/Charts/Charts.vue?vue&type=script&lang=js&
* imports-loader?jQuery=jquery,this=>window!jquery.flot.animator/jquery.flot.animator in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/Charts/Charts.vue?vue&type=script&lang=js&

To install them, you can run: npm install --save core-js/modules/es6.regexp.to-string core-js/modules/es7.promise.finally imports-loader?jQuery=jquery,this=>window!jquery.flot-orderBars/js/jquery.flot.orderBars imports-loader?jQuery=jquery,this=>window!jquery.flot.animator/jquery.flot.animator

**Comment by shiran1989** [comment]
Hi,
try this:
npm install core-js --save
npm install imports-loader --save
npm install

**Comment by elioclimaco** [comment]
> 
> 
> Hi,
> try this:
> npm install core-js --save
> npm install imports-loader --save
> npm install

This works, thank you very much.

**Comment by mnlk66** [comment]
HELLO have similar problems 
 ERROR  Failed to compile with 2 errors                                                                                                                                                                    20:08:38

These dependencies were not found:

* imports-loader?jQuery=jquery,this=>window!jquery.flot-orderBars/js/jquery.flot.orderBars in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/Charts/Charts.vue?vue&type=script&lang=js&
* imports-loader?jQuery=jquery,this=>window!jquery.flot.animator/jquery.flot.animator in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/Charts/Charts.vue?vue&type=script&lang=js&

To install them, you can run: npm install --save imports-loader?jQuery=jquery,this=>window!jquery.flot-orderBars/js/jquery.flot.orderBars imports-loader?jQuery=jquery,this=>window!jquery.flot.animator/jquery.flot.animator


I try to npm install imports-loader --save but dont work
