### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by Wolfeitz** [flatlogic/sing-app-vue-dashboard#3]
C:\1\Projects\TccdSing>npm run serve

> sing-app-vue@4.5.0 serve C:\1\Projects\TccdSing
> vue-cli-service serve

 INFO  Starting development server...
 98% after emitting CopyPlugin
----------------------------------------------------------------------
 ERROR  Failed to compile with 1 errors                           10:17:59 AM

This dependency was not found:

* core-js/modules/es6.regexp.to-string in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/Charts/Charts.vue?vue&type=script&lang=js&
----------------------------------------------------------------------
To install it, you can run: npm install --save core-js/modules/es6.regexp.to-string

**Comment by yashanet** [comment]
same for me

**Comment by madplay** [comment]
me too.
should i do install another package?

**Comment by madplay** [comment]
It's the same for me.
should i do install another package?

**Comment by keksonov** [comment]
@madplay Thank you so much for this fix!
